import {getState,getSlot,setActiveSlot,subscribe,updateSlot,setState} from './state.js';
import {mediaToTexts} from './video.js';import {parseMatchText} from './parser-match.js';import {parseSquadText,dedupePlayers,squadSummary} from './parser-squad.js';import {parseCalendarText,mergeCalendar} from './parser-calendar.js';import {mergeBetter,validateMatch} from './validator.js';import {rivalHuman} from './slots.js';import {generateTactic,generateStrong433} from './tactics-engine.js';import {buildMarketPlan} from './market-engine.js';import {recordResult} from './learning-engine.js';import {apiStatus} from './ai-router.js';import {requestNotifications,scheduleLocal} from './notifications.js';
let root,tab='today',busy=false,statusText='Pronto';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function card(title,body,actions=''){return `<section class="card"><h3>${title}</h3>${body}${actions?`<div class="actions">${actions}</div>`:''}</section>`}
function tabs(){return ['today:Hoje','pregame:Pré-jogo','analyze:Analisar','info:Informações','director:Diretor','learning:Aprendizado'].map(x=>{const[a,b]=x.split(':');return `<button class="tab ${tab===a?'active':''}" data-tab="${a}">${b}</button>`}).join('')}
function field(label,v){return `<div class="field"><span>${label}</span><b class="${v==='NI'||v==null?'ni':''}">${esc(v??'NI')}</b></div>`}
function tacticView(t){if(!t)return '<p class="muted">Nenhuma tática gerada.</p>';return ['formation:Formação','style:Estilo de jogo','pressure:Pressão','mentality:Mentalidade / Estilo','tempo:Ritmo / Temporização','marking:Marcação','offside:Impedimento','tackling:Desarme','attack:Avançadas – Ataque','midfield:Avançadas – Meio','defense:Avançadas – Defesa'].map(x=>{const[k,l]=x.split(':');return field(l,t[k]);}).join('')+`<p class="reason">${esc(t.reason||'')}</p>`}
function today(slot){const next=(slot.calendar||[]).find(x=>!x.result)||slot.calendar?.[0];const pending=!slot.tactics?'Gerar tática':(!slot.match?.referee?'Atualizar partida':null);return card(`Slot ${slot.id} • ${esc(slot.myTeam||'Time não definido')}`,`${field('Próximo jogo',next?.opponent||'NI')}${field('Data',next?`${next.date} ${next.time||''}`:'NI')}${field('Local',next?(next.home?'Casa':'Fora'):'NI')}${field('Status',pending||'Preparação ok')}`,pending?`<button data-go="${pending==='Gerar tática'?'pregame':'analyze'}">Urgente: ${pending}</button>`:'')}
function pregame(slot,state){const v=validateMatch(slot.match||{});return card('Dados da partida',`${field('Minha força',slot.match?.myStrength)}${field('Força rival',slot.match?.rivalStrength)}${field('Árbitro',slot.match?.referee)}${field('Rival',slot.match?.rivalName)}${field('Humano/CPU',slot.match?.human===true?'Humano':slot.match?.human===false?'CPU':'NI')}${field('Formação rival',slot.match?.rivalFormation)}${field('Plano rival',slot.match?.rivalPlan)}${field('Marcação',slot.match?.rivalMarking)}${field('Impedimento',slot.match?.rivalOffside)}${field('Treino secreto',slot.match?.secretTraining)}${field('Campo treinamento',slot.match?.trainingCamp)}<div class="quality"><b>Cobertura:</b> ${v.coverage}% ${v.hiddenByGame.length?'• oculto pelo jogo considerado':''}</div><details><summary>Corrigir / preencher manualmente</summary><div class="manual"><input id="mMyStrength" inputmode="numeric" placeholder="Minha força" value="${esc(slot.match?.myStrength==='NI'?'':slot.match?.myStrength||'')}"><input id="mRivalStrength" inputmode="numeric" placeholder="Força rival" value="${esc(slot.match?.rivalStrength==='NI'?'':slot.match?.rivalStrength||'')}"><select id="mReferee"><option>NI</option>${['Verde','Azul','Amarelo','Laranja','Vermelho'].map(x=>`<option ${slot.match?.referee===x?'selected':''}>${x}</option>`).join('')}</select><input id="mFormation" placeholder="Formação rival" value="${esc(slot.match?.rivalFormation==='NI'?'':slot.match?.rivalFormation||'')}"><input id="mPlan" placeholder="Plano rival" value="${esc(slot.match?.rivalPlan==='NI'?'':slot.match?.rivalPlan||'')}"><select id="mSecret"><option>NI</option><option ${slot.match?.secretTraining==='Sim'?'selected':''}>Sim</option><option ${slot.match?.secretTraining==='Não'?'selected':''}>Não</option></select><button id="saveManual">Salvar correções</button></div></details>`,`<button id="genTactic">Gerar melhor tática</button>${Number(slot.match?.myStrength)-Number(slot.match?.rivalStrength)>=13?'<button class="secondary" id="genStrong">Gerar tática forte 4-3-3</button>':''}`)+card('Tática',tacticView(slot.tactics),slot.tactics?'<button class="secondary" id="registerResult">Registrar resultado</button>':'')}
function analyze(slot){return card('Analisar mídia',`<div class="seg"><button class="analysisType active" data-type="match">Partida</button><button class="analysisType" data-type="squad">Elenco</button><button class="analysisType" data-type="calendar">Calendário</button></div><input id="media" type="file" accept="image/*,video/*" multiple><p class="muted">Selecione vídeo ou várias imagens do OSM no Android. O processamento começa localmente; APIs são fallback.</p><div id="progress">${esc(statusText)}</div>`,`<button id="runAnalysis" ${busy?'disabled':''}>${busy?'Analisando…':'Analisar'}</button>`)}
function info(slot){const s=squadSummary(slot.squad?.players||[]);return card('Elenco',`${field('Total',s.total)}${field('ATA',s.by.ATA)}${field('MEI',s.by.MEI)}${field('DEF',s.by.DEF)}${field('GOL',s.by.GOL)}${field('Treinando',s.training)}${field('À venda',s.forSale)}`)+card('Calendário',`<div class="list">${(slot.calendar||[]).map(r=>`<div><b>${esc(r.date)}</b> ${esc(r.time||'')} • ${esc(r.opponent||'NI')} • ${r.home?'Casa':'Fora'} ${r.cup?'• Copa':''} ${r.result?`• ${r.result}`:''}</div>`).join('')||'<span class="muted">Sem dados.</span>'}</div>`)}
function director(slot){const p=slot.director?.plan;return card('Diretor IA',p?`${field('Força atual',p.currentStrength)}${field('Meta estimada',p.targetStrength)}${field('Horizonte',p.horizon)}<h4>Vendas prioritárias</h4><div class="list">${p.sell.map(x=>`<div>${esc(x.name)} • ${x.position} • ${x.strength}</div>`).join('')||'Nenhuma'}</div><h4>Compras</h4><div class="list">${p.buy.map(x=>`<div>${x.count}× ${x.position}: ${esc(x.profile)}</div>`).join('')||'Completar qualidade, sem inventar nomes do mercado.'}</div>`:'<p class="muted">Gere o plano usando o elenco lido.</p>',`<button id="marketPlan">Atualizar plano do mercado</button>`)}
function learning(slot){return card('Aprendizado IA',`<div class="list">${Object.entries(slot.learning?.weights||{}).map(([k,w])=>`<div><b>${k}</b> • ${w.games} jogos • ${w.wins}V ${w.draws}E ${w.losses}D • peso ${w.weight}</div>`).join('')||'<span class="muted">Registre resultados para aprender.</span>'}</div>`)+card('Histórico',`<div class="list">${(slot.learning?.matches||[]).slice(0,10).map(m=>`<div>${new Date(m.at).toLocaleDateString('pt-BR')} • ${m.outcome} • ${esc(m.tactic?.formation||'NI')}</div>`).join('')||'<span class="muted">Sem resultados.</span>'}</div>`)}
function body(){const state=getState(),slot=getSlot();return tab==='today'?today(slot):tab==='pregame'?pregame(slot,state):tab==='analyze'?analyze(slot):tab==='info'?info(slot):tab==='director'?director(slot):learning(slot)}
async function render(){const state=getState();root.innerHTML=`<header><div><div class="brand">⚽ OSM AI Coach Pro</div><div class="sub">Android • PWA • ${navigator.onLine?'Online':'Offline'}</div></div><button id="notifyBtn" class="iconbtn">🔔</button></header><div class="slots">${[1,2,3,4].map(n=>`<button data-slot="${n}" class="${state.activeSlot===n?'active':''}">S${n}</button>`).join('')}</div><nav>${tabs()}</nav><main>${body()}</main><footer><span>Usuário OSM: leandrozzy</span><span id="apiState">APIs: verificando…</span></footer>`;bind();apiStatus().then(s=>{const e=document.querySelector('#apiState');if(e)e.textContent=s?`APIs: ${Object.entries(s.providers||{}).filter(([,v])=>v).map(([k])=>k).join(', ')||'fallback local'}`:'APIs: fallback local';});}
function bind(){document.querySelectorAll('.analysisType').forEach(b=>b.onclick=()=>{document.querySelectorAll('.analysisType').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{setActiveSlot(Number(b.dataset.slot));render()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{tab=b.dataset.go;render()});document.querySelector('#notifyBtn').onclick=async()=>{await requestNotifications();getState().slots.forEach(scheduleLocal);alert('Notificações locais configuradas para jogos conhecidos.');};
 const sm=document.querySelector('#saveManual');if(sm)sm.onclick=()=>{updateSlot(s=>{const val=id=>document.querySelector(id)?.value?.trim()||'NI';s.match={...s.match,myStrength:val('#mMyStrength'),rivalStrength:val('#mRivalStrength'),referee:val('#mReferee'),rivalFormation:val('#mFormation'),rivalPlan:val('#mPlan'),secretTraining:val('#mSecret')}});render()};
 const g=document.querySelector('#genTactic');if(g)g.onclick=()=>{updateSlot((s,state)=>{s.match.human=rivalHuman(s.match.rivalNickname,s.competitionType,state.settings.username);s.tactics=generateTactic(s.match,state.settings,s.learning)});render()};const gs=document.querySelector('#genStrong');if(gs)gs.onclick=()=>{updateSlot((s,state)=>s.tactics=generateStrong433(s.match,state.settings));render()};
 const mp=document.querySelector('#marketPlan');if(mp)mp.onclick=()=>{updateSlot(s=>s.director.plan=buildMarketPlan(s.squad,null,s.match?.myStrength==='NI'?null:Number(s.match?.myStrength)));render()};
 const rr=document.querySelector('#registerResult');if(rr)rr.onclick=()=>{const score=prompt('Placar (ex.: 2x1):','');if(!score)return;const outcome=prompt('Resultado: V, E ou D','V')?.toUpperCase();if(!['V','E','D'].includes(outcome))return;updateSlot(s=>recordResult(s,{score,outcome}));tab='learning';render()};
 const ra=document.querySelector('#runAnalysis');if(ra)ra.onclick=runAnalysis;}
async function runAnalysis(){const input=document.querySelector('#media');if(!input.files.length)return alert('Selecione ao menos um vídeo ou imagem.');const type=document.querySelector('.analysisType.active')?.dataset.type||'match';busy=true;statusText='Preparando mídia…';render();try{const result=await mediaToTexts([...input.files],u=>{statusText=`OCR ${u.current}/${u.total}`;const p=document.querySelector('#progress');if(p)p.textContent=statusText;});const text=result.texts.join('\n');updateSlot((s,state)=>{if(type==='match'){let parsed=parseMatchText(text);parsed.human=rivalHuman(parsed.rivalNickname||s.match?.rivalNickname,s.competitionType,state.settings.username);s.match=mergeBetter(s.match,parsed);}else if(type==='squad'){s.squad={players:dedupePlayers([...(s.squad?.players||[]),...parseSquadText(text)]),updatedAt:new Date().toISOString()};}else{s.calendar=mergeCalendar(s.calendar||[],parseCalendarText(text));}});statusText=`Concluído: ${result.frameCount} telas únicas processadas.`;tab=type==='match'?'pregame':'info';}catch(e){console.error(e);statusText=`Falha parcial: ${e.message}. Dados antigos foram preservados.`;alert(statusText);}finally{busy=false;render();}}
export function initApp(el){root=el;subscribe(()=>{});render();}
